/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "b1_mux_2_1_case.sv:1" *)
module b1_mux_2_1_case(d0, d1, sel, y);
  (* src = "b1_mux_2_1_case.sv:3" *)
  input d0;
  (* src = "b1_mux_2_1_case.sv:4" *)
  input d1;
  (* src = "b1_mux_2_1_case.sv:5" *)
  input sel;
  (* src = "b1_mux_2_1_case.sv:6" *)
  output y;
  assign y = sel ? d1 : d0;
endmodule
